# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    image: node:13.5.0-alpine
    restart: always
    working_dr: /app
    volumes:
     - ./:/app
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    networks:
      - caddy-node_caddy
    command: npm install && npm run dev

networks:
  caddy-node_caddy:
    external: true