# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    image: node:13.5.0-alpine
    restart: always
    working_dir: /app
    volumes:
     - ./:/app
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - caddy-node_caddy
    command: ./entrypoint.sh 

networks:
  caddy-node_caddy:
    external: true
